### ISSUE TITLE
Check references in Chapter 3

### ISSUE THREAD

**Issue by stschiff** [MPI-EVA-Archaeogenetics/ethics_statement#15]
Hi @nevrome, we have added two references according to your suggestion to Chapter 3 (Shennan and Perreault). Please have a look whether they are i) correct and ii) in the right place. Thank you!

**Comment by stschiff** [comment]
And as a reminder to self -> We need to create a tag and update the Changelog once this is done.

**Comment by nevrome** [comment]
Yes - looks good to me - excellent!

**Comment by stschiff** [comment]
Thanks!
